name: "cacaxx"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: publish
          scope: '@banca21'
      - run: npm ci
      - run: npm publish
        env:
          NPM_SEKRET: ${{ secrets.GITHUB_TOKEN }}
